language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
dist: trusty
sudo: required
addons:
  chrome: stable

branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run test
  - npm run e2e
