language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng test --browsers=ChromeHeadlessNoSandbox
  - ng e2e
